import { useEffect, useState } from 'react';
import { ArrowDown, ArrowRight, Clock3, CloudRain, LocateFixed, Navigation, Route, TrafficCone, TrendingUp } from 'lucide-react';
import type { CitizenAlert, CitizenRoute, TrafficObservation } from '../types';
import { citizenService } from '../services';
import { BottomSheet, MapLegend, MapView, type MapMarker } from '../components/MapView';
import { AppHeader, EmptyState, ErrorState, LoadingState, PageIntro, SectionHeader, SeverityBadge, Surface } from '../components/ui';

export default function CitizenPages({page,navigate,exit}:{page:string;navigate:(x:string)=>void;exit:()=>void}){
 const [traffic,setTraffic]=useState<TrafficObservation[]>();
 const [alerts,setAlerts]=useState<CitizenAlert[]>();
 const [route,setRoute]=useState<CitizenRoute>();
 const [failed,setFailed]=useState(false);
 const [routeDetail,setRouteDetail]=useState(false);
 useEffect(()=>{Promise.all([citizenService.getMapData(),citizenService.recommendRoute()]).then(([map,result])=>{setTraffic(map.traffic);setAlerts(map.alerts);setRoute(result)}).catch(()=>setFailed(true))},[]);
 if(routeDetail&&route)return <><AppHeader title="Route details" subtitle="Simulated journey estimate" onBack={()=>setRouteDetail(false)}/><main><RouteDetail route={route}/></main></>;
 return <><AppHeader title="City Mobility" subtitle="Chennai · Updated 18:44" onExit={exit}/><main>{failed?<ErrorState/>:!traffic||!alerts||!route?<LoadingState/>:<>{page==='traffic'&&<TrafficHome traffic={traffic} alerts={alerts} openMap={()=>navigate('map')} openAlerts={()=>navigate('alerts')}/>} {page==='map'&&<TrafficMap traffic={traffic} findRoute={()=>navigate('routes')}/>} {page==='routes'&&<Routes route={route} view={()=>setRouteDetail(true)}/>} {page==='alerts'&&<Alerts alerts={alerts}/>}</>}</main></>;
}

const markers=(traffic:TrafficObservation[]):MapMarker[]=>traffic.map(x=>({id:x.id,type:'traffic',x:x.mapX,y:x.mapY,label:`${x.road}, ${x.densityLevel} traffic`,detail:x.densityLevel}));

function TrafficHome({traffic,alerts,openMap,openAlerts}:{traffic:TrafficObservation[];alerts:CitizenAlert[];openMap:()=>void;openAlerts:()=>void}){const main=traffic[0];return <div className="citizen-home"><div className="city-greeting"><span>CITY MOBILITY</span><h1>Current traffic</h1><p>Live conditions from the city's public transport sensing network.</p></div><div className="home-map"><MapView markers={markers(traffic)} onSelect={openMap} mode="traffic"><MapLegend mode="traffic"/><button className="map-open" onClick={openMap}>Explore map <ArrowRight/></button><div className="traffic-summary"><span>TRAFFIC STATUS<strong>{main.densityLevel}</strong></span><span>LAST UPDATED<strong>{main.timestamp}</strong></span></div></MapView></div><div className="nearby"><SectionHeader title="Nearby conditions" action="View alerts" onAction={openAlerts}/>{alerts.map(a=><div className="nearby-row" key={a.id}><i className={a.type.toLowerCase()}>{a.type==='Waterlogging'?<CloudRain/>:<TrafficCone/>}</i><div><strong>{a.title}</strong><span>{a.location}</span></div><b>{a.distance}</b></div>)}</div></div>}

function TrafficMap({traffic,findRoute}:{traffic:TrafficObservation[];findRoute:()=>void}){const [selected,setSelected]=useState(traffic[0].id);const segment=traffic.find(x=>x.id===selected);return <div className="map-page citizen-full-map"><MapView markers={markers(traffic)} selected={selected} onSelect={setSelected} mode="traffic"><MapLegend mode="traffic"/>{segment&&<BottomSheet eyebrow={`${segment.road.toUpperCase()} · UPDATED ${segment.timestamp}`} title={`${segment.densityLevel} traffic`} action={segment.id==='TR-1'?'Find a better route':undefined} onAction={segment.id==='TR-1'?findRoute:undefined}><div className="traffic-facts"><span>Vehicle density<strong>{segment.densityLevel==='Severe'?'Very high':segment.densityLevel}</strong></span><span>Average speed<strong>{segment.averageSpeed} km/h</strong></span><span>Trend<strong><TrendingUp/> {segment.trend}</strong></span></div><p className="fleet-source">Why is this shown? <strong>Observed by public transport fleet</strong></p><small>Recommended: {segment.recommendedAction}</small></BottomSheet>}</MapView></div>}

function Routes({route,view}:{route:CitizenRoute;view:()=>void}){return <div className="page"><PageIntro eyebrow="FLEET-OBSERVED CONDITIONS" title="A better route" text={`From ${route.origin} to ${route.destination}`}/><div className="route-saving"><span>SAVE</span><strong>{route.currentMinutes-route.alternativeMinutes} min</strong></div><div className="route-compare"><div className="route old"><i/><div><span>Current route</span><strong>{route.currentMinutes} min</strong><small>Via Anna Salai · Heavy traffic</small></div></div><div className="route recommended"><i/><div><span>Recommended · Route B</span><strong>{route.alternativeMinutes} min</strong><small>Via {route.via}</small></div><b>{route.traffic}</b></div></div><Surface className="route-reason"><Navigation/><div><strong>Why this route?</strong><p>{route.reason}, observed across recent public transport fleet passes.</p></div></Surface><button className="primary full" onClick={view}>View route <ArrowRight/></button><p className="disclaimer">Demo recommendation only. This prototype does not replace turn-by-turn navigation.</p></div>}

function RouteDetail({route}:{route:CitizenRoute}){return <div className="page"><PageIntro eyebrow="RECOMMENDED · ROUTE B" title={`${route.alternativeMinutes} min to ${route.destination}`} text={`${route.origin} → ${route.destination}`}/><Surface className="route-overview"><div><span>Origin<strong>{route.origin}</strong></span><span>Destination<strong>{route.destination}</strong></span><span>Estimated time<strong>{route.alternativeMinutes} min</strong></span><span>Traffic<strong>{route.traffic}</strong></span></div></Surface><div className="route-visual" aria-label={`Route from ${route.origin} to ${route.destination}`}>{route.stops.map((stop,index)=><div key={stop}><i>{index===0?'START':index===route.stops.length-1?'END':index}</i><strong>{stop.replace('Start · ','')}</strong>{index<route.stops.length-1&&<ArrowDown/>}</div>)}</div><Surface className="route-reason"><Navigation/><div><strong>Avoiding</strong><p>{route.avoiding}</p><strong>Why recommended</strong><p>{route.reason} · Traffic is {route.traffic.toLowerCase()}.</p></div></Surface></div>}

function Alerts({alerts}:{alerts:CitizenAlert[]}){const icons={Traffic:TrafficCone,Waterlogging:CloudRain,Obstruction:Route};return <div className="page"><PageIntro eyebrow="NEARBY UPDATES" title="Mobility alerts" text="Important conditions that may affect your journey"/>{alerts.length===0?<EmptyState title="No nearby alerts"/>:<div className="alert-list">{alerts.map(x=>{const Icon=icons[x.type];return <div className="alert-row" key={x.id}><i className={x.type==='Waterlogging'?'blue':''}><Icon/></i><div><strong>{x.title}</strong><span><LocateFixed/> {x.location}</span></div><small><Clock3/> {x.timeAgo}</small></div>})}</div>}<SectionHeader title="Road conditions"/><div className="condition-list"><Surface><div><strong>Pothole · OMR</strong><span>Observed recently</span></div><SeverityBadge value="High"/></Surface><Surface><div><strong>Waterlogging · Guindy</strong><span>May affect low-clearance vehicles</span></div><SeverityBadge value="Medium"/></Surface><Surface><div><strong>Road obstruction · Saidapet</strong><span>Use caution</span></div><SeverityBadge value="Low"/></Surface></div></div>}
