import { useState } from 'react';
import { ArrowRight, Check, Clock3, CloudRain, LocateFixed, Navigation, Route, TrafficCone, TrendingUp } from 'lucide-react';
import { traffic } from '../data/demo';
import { BottomSheet, MapLegend, MapView } from '../components/MapView';
import { AppHeader, PageIntro, SectionHeader, Surface } from '../components/ui';
export default function CitizenPages({page,navigate,exit}:{page:string;navigate:(x:string)=>void;exit:()=>void}){return <><AppHeader title="City Mobility" subtitle="Chennai · Updated just now" onExit={exit}/><main>{(page==='traffic'||page==='map')&&<Traffic go={()=>navigate('routes')}/>} {page==='routes'&&<Routes/>} {page==='alerts'&&<Alerts/>}</main></>}
function Traffic({go}:{go:()=>void}){const [sel,setSel]=useState('t1');const m:any[]=[{id:'t1',type:'traffic',x:55,y:38,label:'Anna Salai'},{id:'t2',type:'traffic',x:72,y:65,label:'OMR'}];return <div className="citizen-map"><div className="city-greeting"><span>THURSDAY · 18:45</span><h1>How is Chennai moving?</h1><p>Live road conditions observed by the city fleet</p></div><MapView markers={m} selected={sel} onSelect={setSel} mode="traffic"><MapLegend mode="traffic"/>{sel&&<BottomSheet eyebrow="ANNA SALAI · UPDATED 18:44" title="Heavy traffic" action="Find a faster route" onAction={go}><div className="traffic-facts"><span>Vehicle density<strong>High</strong></span><span>Average speed<strong>18 km/h</strong></span><span>Trend<strong><TrendingUp/> Increasing</strong></span></div></BottomSheet>}</MapView></div>}
function Routes(){const [used,setUsed]=useState(false);return <div className="page"><PageIntro eyebrow="FLEET-OBSERVED CONDITIONS" title="A faster way around" text="Avoid heavy traffic on Anna Salai"/><div className="route-compare"><div className="route old"><i/><div><span>Current route</span><strong>38 min</strong><small>Via Anna Salai · Heavy traffic</small></div></div><div className="route recommended"><i/><div><span>Recommended · Route B</span><strong>24 min</strong><small>Via C.P. Ramaswamy Road</small></div><b>14 min faster</b></div></div><Surface className="route-reason"><Navigation/><div><strong>Why this route?</strong><p>Lower observed vehicle density across recent public transport fleet passes.</p></div></Surface><button className="primary full" onClick={()=>setUsed(true)}>{used?<><Check/> Route selected</>:<>Use alternate route <ArrowRight/></>}</button><p className="disclaimer">Travel estimates are simulated for this demonstration.</p></div>}
function Alerts(){const alerts=[{icon:TrafficCone,title:'Heavy traffic detected',place:'Anna Salai',time:'5 min ago',tone:'red'},{icon:CloudRain,title:'Waterlogging reported',place:'Guindy',time:'12 min ago',tone:'blue'},{icon:Route,title:'Road obstruction',place:'OMR',time:'18 min ago',tone:'amber'}];return <div className="page"><PageIntro eyebrow="NEARBY UPDATES" title="Mobility alerts" text="Useful road updates, without operational clutter"/><div className="alert-list">{alerts.map(({icon:Icon,...x})=><div className="alert-row"><i className={x.tone}><Icon/></i><div><strong>{x.title}</strong><span><LocateFixed/> {x.place}</span></div><small><Clock3/> {x.time}</small></div>)}</div><SectionHeader title="Alert preferences"/><Surface className="preference"><span>Only show alerts near my route</span><button className="toggle"><i/></button></Surface></div>}
