import { useEffect, useRef, useState } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { ArrowRight, BusFront, CalendarCheck, Construction, History, MapPin, School, Signpost, TrafficCone, Wrench } from 'lucide-react';
import { defects } from '../data/demo';
import type { RoadDefect } from '../types';
import { DefectCard } from '../components/cards';
import { AppHeader, FilterBar, MetricCard, PageIntro, SectionHeader, SeverityBadge, Surface } from '../components/ui';
import { MunicipalMapView, type MunicipalGeoMarker, type MunicipalMapCamera } from '../components/MunicipalMapView';
import { PotholeLifecycle } from '../components/PotholeLifecycle';

type View={kind:'detail'|'lifecycle';id:string}|{kind:'result';road:string;duration:string};
type Diversion={name:string;points:L.LatLngExpression[];impact:'High'|'Severe'};
type Road={id:string;name:string;points:L.LatLngExpression[];baseline:string;baselineMinutes:number;delay:number;sample:number;busRoutes:string[];diversions:Diversion[]};
const roads:Road[]=[
 {id:'anna',name:'Anna Salai · Teynampet',points:[[13.0607,80.2496],[13.0524,80.2457],[13.0418,80.2341],[13.0314,80.2293]],baseline:'Moderate',baselineMinutes:24,delay:11,sample:1284,busRoutes:['5E','23C','27D'],diversions:[{name:'C.P. Ramaswamy Road',points:[[13.0418,80.2341],[13.0375,80.249],[13.0289,80.2554]],impact:'High'},{name:'Cathedral Road',points:[[13.0524,80.2457],[13.0512,80.2571],[13.043,80.2584]],impact:'Severe'}]},
 {id:'omr',name:'OMR · Madhya Kailash',points:[[13.0128,80.2512],[13.0065,80.2572],[12.995,80.2605],[12.981,80.256]],baseline:'Heavy',baselineMinutes:31,delay:16,sample:1642,busRoutes:['19B','21D','M70'],diversions:[{name:'L.B. Road',points:[[13.0128,80.2512],[13.006,80.2502],[12.9958,80.254]],impact:'Severe'},{name:'Velachery Main Road',points:[[12.9958,80.254],[12.9862,80.238],[12.9815,80.2209]],impact:'High'}]},
 {id:'velachery',name:'Velachery Main Road',points:[[13.0067,80.2206],[12.9957,80.2214],[12.9815,80.2209],[12.975,80.2212]],baseline:'Moderate',baselineMinutes:22,delay:9,sample:936,busRoutes:['7M','51A'],diversions:[{name:'GST Road',points:[[12.9957,80.2214],[12.9947,80.2088],[12.9824,80.2017]],impact:'High'},{name:'Inner Ring Road',points:[[13.0067,80.2206],[13.0162,80.211],[13.0251,80.206]],impact:'High'}]}
];
const durationScenarios={'2 weeks':{multiplier:.75,days:14,label:'Short works window'},'8 weeks':{multiplier:1,days:56,label:'Staged construction'},'4 months':{multiplier:1.35,days:120,label:'Extended closure'}} as const;
export default function MunicipalOperations({page,navigate,exit}:{page:string;navigate:(x:string)=>void;exit:()=>void}){
 const [stack,setStack]=useState<View[]>([]);const [issueFilter,setIssueFilter]=useState('All');const [mapFilter,setMapFilter]=useState<MunicipalLayer>('Road defects');const [mapSelected,setMapSelected]=useState(defects.find(x=>inMunicipalLayer(x,'Road defects'))?.id||defects[0].id);const [mapViews,setMapViews]=useState<Partial<Record<MunicipalLayer,MunicipalMapCamera>>>({});const [planningRoad,setPlanningRoad]=useState(roads[0].id);const [planningDuration,setPlanningDuration]=useState('8 weeks');const open=(view:View)=>{setStack(s=>[...s,view]);history.pushState({municipal:true},'')};const back=()=>history.back();const home=()=>{setStack([]);navigate('overview')};
 useEffect(()=>{const pop=()=>setStack(s=>s.slice(0,-1));const reset=()=>setStack([]);addEventListener('popstate',pop);addEventListener('workspace-home',reset);return()=>{removeEventListener('popstate',pop);removeEventListener('workspace-home',reset)}},[]);
 const active=stack.at(-1);if(active?.kind==='detail')return <Detail id={active.id} back={back} home={home} lifecycle={()=>open({kind:'lifecycle',id:active.id})}/>;if(active?.kind==='lifecycle')return <Lifecycle id={active.id} back={back} home={home}/>;if(active?.kind==='result')return <Result roadId={active.road} duration={active.duration} back={back} home={home}/>;
 const openItem=(item:RoadDefect)=>open({kind:'detail',id:item.id});const showIssues=(filter:string)=>{setIssueFilter(filter);navigate('defects')};return <><AppHeader title="Municipal Operations" subtitle="Chennai Zone Network · Live" onHome={home} onExit={exit}/><main>{page==='overview'&&<Overview go={navigate} showIssues={showIssues} open={openItem}/>} {page==='defects'&&<IssueList filter={issueFilter} onFilter={setIssueFilter} open={openItem}/>} {page==='map'&&<MunicipalMap filter={mapFilter} selected={mapSelected} view={mapViews[mapFilter]} onFilter={setMapFilter} onSelect={setMapSelected} onViewChange={camera=>setMapViews(views=>({...views,[mapFilter]:camera}))} open={openItem}/>} {page==='planning'&&<Planning selected={planningRoad} duration={planningDuration} onRoad={setPlanningRoad} onDuration={setPlanningDuration} run={()=>open({kind:'result',road:planningRoad,duration:planningDuration})}/>}</main></>;
}
function Overview({go,showIssues,open}:{go:(x:string)=>void;showIssues:(filter:string)=>void;open:(x:RoadDefect)=>void}){return <div className="page municipal-overview"><PageIntro eyebrow="MUNICIPAL OPERATIONS · UPDATED 18:45" title="City Road Health"/><div className="metric-grid compact operations-metrics"><MetricCard label="Open defects" value="42" tone="open" meta="6 added today"/><MetricCard label="Critical" value="07" tone="critical" meta="Needs action"/><MetricCard label="Infrastructure" value="13" tone="infrastructure" meta="4 categories"/><MetricCard label="Verification" value="08" tone="water" meta="Pending passes"/></div><div className="sensor-strip municipal"><BusFront/><div><strong>1,284 road observations today</strong><span>82% route coverage · 238 buses reporting</span></div></div><SectionHeader title="Priority road issue" action="View all" onAction={()=>showIssues('All')}/><DefectCard item={defects[0]} onClick={()=>open(defects[0])}/><SectionHeader title="Operations"/><div className="capability-list"><Capability icon={<Wrench/>} title="Road Defect Detection" meta="42 active records" action={()=>showIssues('Roads')}/><Capability icon={<Signpost/>} title="Infrastructure Monitoring" meta="Crossings, dividers and signs" action={()=>showIssues('Infrastructure')}/><Capability icon={<School/>} title="Pedestrian / School-Crossing Risk" meta="7 locations under review" action={()=>showIssues('Pedestrians')}/><Capability icon={<History/>} title="Road Lifecycle & Repair Verification" meta="Condition history from repeated passes" action={()=>open(defects[0])}/><Capability icon={<TrafficCone/>} title="Traffic & Route Analytics" meta="Live network conditions" action={()=>go('map')}/><Capability icon={<Construction/>} title="Urban Planning & What-If" meta="Evaluate closure scenarios" action={()=>go('planning')}/></div></div>}
function Capability({icon,title,meta,action}:{icon:React.ReactNode;title:string;meta:string;action:()=>void}){return <button onClick={action}>{icon}<span><strong>{title}</strong><small>{meta}</small></span><ArrowRight/></button>}
function IssueList({filter,onFilter,open}:{filter:string;onFilter:(value:string)=>void;open:(x:RoadDefect)=>void}){const visible=defects.filter(x=>filter==='All'||x.category===filter);return <div className="page"><PageIntro eyebrow="FLEET OBSERVATIONS · UPDATED 18:45" title="Road & infrastructure"/><FilterBar items={['All','Roads','Infrastructure','Water','Pedestrians']} active={filter} onChange={onFilter}/><div className="list-stack">{visible.map(x=><DefectCard item={x} key={x.id} onClick={()=>open(x)}/>)}</div></div>}
function Detail({id,back,home,lifecycle}:{id:string;back:()=>void;home:()=>void;lifecycle:()=>void}){const x=defects.find(d=>d.id===id);if(!x)return <><AppHeader title="Record unavailable" subtitle={id} onBack={back} onHome={home}/><main className="page detail"><PageIntro eyebrow="MUNICIPAL RECORD" title="This record is no longer available"/></main></>;const road=x.category==='Roads'||x.category==='Water';return <><AppHeader title={road?'Defect record':'Infrastructure record'} subtitle={x.id} onBack={back} onHome={home}/><main className="page detail"><div className="title-row"><div><span className="eyebrow">{x.category.toUpperCase()} · FLEET EVIDENCE</span><h1>{x.defectType}</h1><p><MapPin/> {x.location}</p></div><SeverityBadge value={x.severity}/></div><div className="road-frame"><img src={x.image} alt={`${x.defectType} observation`}/><span>LATEST EVIDENCE</span><em>{x.lastSeen} · {x.busIds.at(-1)}</em></div><Surface className="detail-facts"><div><span>First observed</span><strong>{x.firstSeen}</strong></div><div><span>Latest observation</span><strong>{x.lastSeen}</strong></div><div><span>Current condition</span><strong>{x.repairStatus||x.status}</strong></div><div><span>Evidence</span><strong>{x.detectionCount} observations · {x.busIds.length} buses</strong></div></Surface>{x.repair&&<Surface className="verification"><CalendarCheck/><div><span>REPAIR {x.repair.result.toUpperCase()}</span><strong>{x.repair.detail}</strong><p>{x.repair.nextObservation} · {x.repair.busId}</p></div></Surface>}{road&&<button className="primary full" onClick={lifecycle}>Open condition lifecycle <ArrowRight/></button>}</main></>}
function Lifecycle({id,back,home}:{id:string;back:()=>void;home:()=>void}){const x=defects.find(d=>d.id===id);if(!x)return null;return <><AppHeader title="Road Condition Intelligence" subtitle={x.id} onBack={back} onHome={home}/><main className="page detail"><PageIntro eyebrow="FLEET-DERIVED CONDITION HISTORY" title={x.location}/><PotholeLifecycle defect={x}/></main></>}

type MunicipalLayer='Road defects'|'Infrastructure'|'Pedestrian risks';
const municipalLayers:MunicipalLayer[]=['Road defects','Infrastructure','Pedestrian risks'];
const inMunicipalLayer=(item:RoadDefect,layer:MunicipalLayer)=>layer==='Road defects'?item.category==='Roads'||item.category==='Water':layer==='Infrastructure'?item.category==='Infrastructure':item.category==='Pedestrians';
function MunicipalMap({filter,selected,view,onFilter,onSelect,onViewChange,open}:{filter:MunicipalLayer;selected:string;view?:MunicipalMapCamera;onFilter:(value:MunicipalLayer)=>void;onSelect:(id:string)=>void;onViewChange:(camera:MunicipalMapCamera)=>void;open:(x:RoadDefect)=>void}){const visible=defects.filter(x=>inMunicipalLayer(x,filter));const item=visible.find(x=>x.id===selected);const markers:MunicipalGeoMarker[]=visible.map(x=>({id:x.id,type:x.category==='Infrastructure'?'infrastructure':x.category==='Pedestrians'?'pedestrian':'road',latitude:x.latitude,longitude:x.longitude,label:`${x.defectType} · ${x.location}`}));const changeFilter=(value:string)=>{const next=value as MunicipalLayer;onFilter(next);const first=defects.find(x=>inMunicipalLayer(x,next));if(first)onSelect(first.id)};return <div className="map-page municipal-map-page"><div className="map-filter"><FilterBar items={municipalLayers} active={filter} onChange={changeFilter}/></div><MunicipalMapView markers={markers} selected={selected} initialView={view} onSelect={onSelect} onViewChange={onViewChange}/>{item&&<section className="bottom-sheet"><i className="handle"/><span className="sheet-eyebrow">{item.severity.toUpperCase()} · {item.category.toUpperCase()}</span><h3>{item.defectType}</h3><p>{item.location} · {item.status}</p><small>{item.detectionCount} observations · Last seen {item.lastSeen}</small><button className="primary" onClick={()=>open(item)}>Open record</button></section>}</div>}

function Planning({selected,duration,onRoad,onDuration,run}:{selected:string;duration:string;onRoad:(id:string)=>void;onDuration:(value:string)=>void;run:()=>void}){const road=roads.find(x=>x.id===selected)!;return <div className="page planning-page"><PageIntro eyebrow="FLEET-DERIVED TRAFFIC BASELINE" title="Urban Planning & What-If"/><Surface className="planning-controls"><strong>1 · Select a road segment on the map</strong><span>Tap any highlighted corridor · Selected: {road.name}</span></Surface><ScenarioMap selected={selected} onSelect={onRoad}/><Surface className="form"><label>Closure / construction duration<select value={duration} onChange={e=>onDuration(e.target.value)}><option>2 weeks</option><option>8 weeks</option><option>4 months</option></select></label><div className="baseline-row"><span>Observed baseline<strong>{road.baseline} · {road.baselineMinutes} min</strong></span><span>Fleet sample<strong>{road.sample.toLocaleString()} passes</strong></span></div><button className="primary full" onClick={run}><Construction/> Run simulation</button></Surface></div>}
function ScenarioMap({selected,onSelect,result=false}:{selected:string;onSelect?:(id:string)=>void;result?:boolean}){const host=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),layer=useRef<L.LayerGroup|null>(null);useEffect(()=>{if(!host.current||map.current)return;map.current=L.map(host.current,{zoomControl:false}).setView([13.02,80.239],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map.current);layer.current=L.layerGroup().addTo(map.current);return()=>{map.current?.remove();map.current=null;layer.current=null}},[]);useEffect(()=>{if(!layer.current||!map.current)return;layer.current.clearLayers();const activeRoad=roads.find(road=>road.id===selected)||roads[0];if(result){L.polyline(activeRoad.points,{color:'#aa3f38',weight:10,opacity:.95,dashArray:'10 7'}).bindTooltip(`${activeRoad.name} · CLOSED`).addTo(layer.current);activeRoad.diversions.forEach(diversion=>L.polyline(diversion.points,{color:diversion.impact==='Severe'?'#7a2d35':'#d07b2e',weight:7,opacity:.9}).bindTooltip(`${diversion.name} · ${diversion.impact} diversion impact`).addTo(layer.current!));const bounds=L.latLngBounds([...activeRoad.points,...activeRoad.diversions.flatMap(diversion=>diversion.points)]);map.current.fitBounds(bounds,{padding:[24,24],maxZoom:14,animate:false});return;}roads.forEach(road=>{const active=road.id===selected;const choose=()=>onSelect?.(road.id);L.polyline(road.points,{color:active?'#b43a3a':'#315c51',weight:active?10:7,opacity:active?1:.75,dashArray:active?'10 7':undefined}).bindTooltip(active?`${road.name} · SELECTED`:road.name).on('click',choose).addTo(layer.current!);const anchor=road.points[Math.floor(road.points.length/2)];L.marker(anchor,{title:`Select ${road.name}`,alt:`Select ${road.name}`,keyboard:true,icon:L.divIcon({className:`scenario-road-label${active?' active':''}`,html:`<span>${road.name.split(' · ')[0]}</span>`,iconSize:[112,34],iconAnchor:[56,17]})}).on('click',choose).addTo(layer.current!)});map.current.fitBounds(L.latLngBounds(roads.flatMap(road=>road.points)),{padding:[34,34],maxZoom:13,animate:false});},[selected,onSelect,result]);return <div className="scenario-map" ref={host} aria-label={result?'Closure and diversion impact map':'Select a road segment for scenario modelling'}/>}
function ImpactChart({baseline,delay,days}:{baseline:number;delay:number;days:number}){const factors=[.35,.72,1,.82,.58];const simulated=factors.map(factor=>baseline+Math.round(delay*factor));const x=(index:number)=>10+index*20;const y=(value:number)=>88-(value/(baseline+delay+5))*68;const baselinePoints=factors.map((_,index)=>`${x(index)},${y(baseline)}`).join(' ');const simulatedPoints=simulated.map((value,index)=>`${x(index)},${y(value)}`).join(' ');return <div className="impact-chart"><div className="chart-legend"><span className="baseline-key">Observed baseline</span><span className="simulated-key">Closure scenario</span></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label={`Baseline ${baseline} minutes compared with simulated peak ${baseline+delay} minutes over ${days} days`}><rect className="closure-window" x="10" y="8" width="80" height="80"/><line className="impact-grid" x1="10" y1="88" x2="90" y2="88"/><polyline className="baseline-line" points={baselinePoints}/><polyline className="simulated-line" points={simulatedPoints}/>{simulated.map((value,index)=><circle key={index} className="impact-point" cx={x(index)} cy={y(value)} r="1.8"/>)}</svg><div className="chart-axis"><span>Start</span><span>Peak</span><span>Adaptation</span><span>Day {days}</span></div><div className="chart-values"><span>{baseline} min baseline</span><strong>{baseline+delay} min peak</strong></div></div>}
function Result({roadId,duration,back,home}:{roadId:string;duration:string;back:()=>void;home:()=>void}){const road=roads.find(x=>x.id===roadId)||roads[0];const scenario=durationScenarios[duration as keyof typeof durationScenarios]||durationScenarios['8 weeks'];const delay=Math.round(road.delay*scenario.multiplier);return <><AppHeader title="Scenario result" subtitle={`${road.name} · ${duration}`} onBack={back} onHome={home}/><main className="page detail"><div className="scenario-compare"><span>OBSERVED<strong>{road.baselineMinutes} min</strong><small>{road.baseline} baseline</small></span><ArrowRight/><span>SIMULATED PEAK<strong>{road.baselineMinutes+delay} min</strong><small>{scenario.label}</small></span></div><ScenarioMap selected={road.id} result/><div className="impact"><span>ESTIMATED AVERAGE DELAY</span><div><strong>+{delay} min</strong><p>During a {scenario.days}-day closure window</p></div><ul>{road.diversions.map(diversion=><li key={diversion.name}>{diversion.name} <b>{diversion.impact}</b></li>)}<li>Bus routes affected <b>{road.busRoutes.join(', ')}</b></li></ul></div><Surface><SectionHeader title="Baseline vs simulated travel time"/><ImpactChart baseline={road.baselineMinutes} delay={delay} days={scenario.days}/></Surface><Surface className="scenario-note"><Construction/><div><strong>Planning estimate</strong><p>Calculated from {road.sample.toLocaleString()} observed fleet passes; actual conditions vary with demand and works phasing.</p></div></Surface></main></>}
