import { useEffect, useRef, useState } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { ArrowRight, BusFront, CalendarCheck, Check, Construction, History, MapPin, School, Signpost, TrafficCone, Wrench } from 'lucide-react';
import { defects } from '../data/demo';
import type { RoadDefect } from '../types';
import { DefectCard } from '../components/cards';
import { AppHeader, FilterBar, MetricCard, PageIntro, SectionHeader, SeverityBadge, Surface } from '../components/ui';

type View={kind:'detail'|'lifecycle';id:string}|{kind:'result';road:string;duration:string};
type Road={id:string;name:string;points:L.LatLngExpression[];baseline:string;delay:number;affected:string[]};
const roads:Road[]=[
 {id:'anna',name:'Anna Salai · Teynampet',points:[[13.0607,80.2496],[13.0524,80.2457],[13.0418,80.2341],[13.0314,80.2293]],baseline:'Moderate',delay:11,affected:['C.P. Ramaswamy Road','Cathedral Road']},
 {id:'omr',name:'OMR · Madhya Kailash',points:[[13.0128,80.2512],[13.0065,80.2572],[12.995,80.2605],[12.981,80.256]],baseline:'Heavy',delay:16,affected:['L.B. Road','Velachery Main Road']},
 {id:'velachery',name:'Velachery Main Road',points:[[13.0067,80.2206],[12.9957,80.2214],[12.9815,80.2209],[12.975,80.2212]],baseline:'Moderate',delay:9,affected:['GST Road','Inner Ring Road']}
];
export default function MunicipalOperations({page,navigate,exit}:{page:string;navigate:(x:string)=>void;exit:()=>void}){
 const [stack,setStack]=useState<View[]>([]);const [planningRoad,setPlanningRoad]=useState(roads[0].id);const [planningDuration,setPlanningDuration]=useState('8 weeks');const open=(view:View)=>{setStack(s=>[...s,view]);history.pushState({municipal:true},'')};const back=()=>history.back();const home=()=>{setStack([]);navigate('overview')};
 useEffect(()=>{const pop=()=>setStack(s=>s.slice(0,-1));const reset=()=>setStack([]);addEventListener('popstate',pop);addEventListener('workspace-home',reset);return()=>{removeEventListener('popstate',pop);removeEventListener('workspace-home',reset)}},[]);
 const active=stack.at(-1);if(active?.kind==='detail')return <Detail id={active.id} back={back} home={home} lifecycle={()=>open({kind:'lifecycle',id:active.id})}/>;if(active?.kind==='lifecycle')return <Lifecycle id={active.id} back={back} home={home}/>;if(active?.kind==='result')return <Result roadId={active.road} duration={active.duration} back={back} home={home}/>;
 const openItem=(item:RoadDefect)=>open({kind:'detail',id:item.id});return <><AppHeader title="Municipal Operations" subtitle="Chennai Zone Network · Live" onHome={home} onExit={exit}/><main>{page==='overview'&&<Overview go={navigate} open={openItem}/>} {page==='defects'&&<IssueList open={openItem}/>} {page==='map'&&<MunicipalMap open={openItem}/>} {page==='planning'&&<Planning selected={planningRoad} duration={planningDuration} onRoad={setPlanningRoad} onDuration={setPlanningDuration} run={()=>open({kind:'result',road:planningRoad,duration:planningDuration})}/>}</main></>;
}
function Overview({go,open}:{go:(x:string)=>void;open:(x:RoadDefect)=>void}){return <div className="page municipal-overview"><PageIntro eyebrow="MUNICIPAL OPERATIONS · UPDATED 18:45" title="City Road Health"/><div className="metric-grid compact operations-metrics"><MetricCard label="Open defects" value="42" meta="6 added today"/><MetricCard label="Critical" value="07" tone="critical" meta="Needs action"/><MetricCard label="Infrastructure" value="13" meta="4 categories"/><MetricCard label="Verification" value="08" tone="water" meta="Pending passes"/></div><div className="sensor-strip municipal"><BusFront/><div><strong>1,284 road observations today</strong><span>82% route coverage · 238 buses reporting</span></div></div><SectionHeader title="Priority road issue" action="View all" onAction={()=>go('defects')}/><DefectCard item={defects[0]} onClick={()=>open(defects[0])}/><SectionHeader title="Operations"/><div className="capability-list"><Capability icon={<Wrench/>} title="Road Defect Detection" meta="42 active records" action={()=>go('defects')}/><Capability icon={<Signpost/>} title="Infrastructure Monitoring" meta="Crossings, dividers and signs" action={()=>go('defects')}/><Capability icon={<School/>} title="Pedestrian / School-Crossing Risk" meta="7 locations under review" action={()=>go('defects')}/><Capability icon={<History/>} title="Road Lifecycle & Repair Verification" meta="Condition history from repeated passes" action={()=>open(defects[0])}/><Capability icon={<TrafficCone/>} title="Traffic & Route Analytics" meta="Live network conditions" action={()=>go('map')}/><Capability icon={<Construction/>} title="Urban Planning & What-If" meta="Evaluate closure scenarios" action={()=>go('planning')}/></div></div>}
function Capability({icon,title,meta,action}:{icon:React.ReactNode;title:string;meta:string;action:()=>void}){return <button onClick={action}>{icon}<span><strong>{title}</strong><small>{meta}</small></span><ArrowRight/></button>}
function IssueList({open}:{open:(x:RoadDefect)=>void}){const [filter,setFilter]=useState('All');const visible=defects.filter(x=>filter==='All'||x.category===filter);return <div className="page"><PageIntro eyebrow="FLEET OBSERVATIONS · UPDATED 18:45" title="Road & infrastructure"/><FilterBar items={['All','Roads','Infrastructure','Water','Pedestrians']} active={filter} onChange={setFilter}/><div className="list-stack">{visible.map(x=><DefectCard item={x} key={x.id} onClick={()=>open(x)}/>)}</div></div>}
function Detail({id,back,home,lifecycle}:{id:string;back:()=>void;home:()=>void;lifecycle:()=>void}){const x=defects.find(d=>d.id===id)||defects[0];const road=x.category==='Roads'||x.category==='Water';return <><AppHeader title={road?'Defect record':'Infrastructure record'} subtitle={x.id} onBack={back} onHome={home}/><main className="page detail"><div className="title-row"><div><span className="eyebrow">{x.category.toUpperCase()} · FLEET EVIDENCE</span><h1>{x.defectType}</h1><p><MapPin/> {x.location}</p></div><SeverityBadge value={x.severity}/></div><div className="road-frame"><img src={x.image} alt={`${x.defectType} observation`}/><span>LATEST EVIDENCE</span><em>{x.lastSeen} · {x.busIds.at(-1)}</em></div><Surface className="detail-facts"><div><span>First observed</span><strong>{x.firstSeen}</strong></div><div><span>Latest observation</span><strong>{x.lastSeen}</strong></div><div><span>Current condition</span><strong>{x.repairStatus||x.status}</strong></div><div><span>Evidence</span><strong>{x.detectionCount} observations · {x.busIds.length} buses</strong></div></Surface>{x.repair&&<Surface className="verification"><CalendarCheck/><div><span>REPAIR {x.repair.result.toUpperCase()}</span><strong>{x.repair.detail}</strong><p>{x.repair.nextObservation} · {x.repair.busId}</p></div></Surface>}{road&&<button className="primary full" onClick={lifecycle}>Open condition lifecycle <ArrowRight/></button>}</main></>}
function Lifecycle({id,back,home}:{id:string;back:()=>void;home:()=>void}){const x=defects.find(d=>d.id===id)||defects[0];const obs=x.observations||[];const stages=[...obs.map((o,i)=>({label:['Detected','Observed','Degrading','High risk'][i]||'High risk',date:o.date,detail:o.label,bus:o.busId,tone:i<2?'stable':'risk'})),{label:'Repair',date:x.repair?.markedRepaired||'Pending',detail:'Municipal intervention recorded',bus:'Works record',tone:'repair'},{label:'Verified',date:x.repair?.nextObservation||'Next pass',detail:x.repair?.detail||'Awaiting post-repair evidence',bus:x.repair?.busId||'Fleet verification',tone:x.repair?.result==='Verified'?'verified':'pending'}];return <><AppHeader title="Road Condition Intelligence" subtitle={x.id} onBack={back} onHome={home}/><main className="page detail"><PageIntro eyebrow="REPEATED FLEET OBSERVATIONS" title={x.location}/><div className="lifecycle-flow">{stages.map((s,i)=><div className={s.tone} key={`${s.label}-${i}`}><i>{s.tone==='verified'?<Check/>:i+1}</i><div><span>{s.label.toUpperCase()} · {s.date}</span><strong>{s.detail}</strong><small>{s.bus}</small></div>{i<stages.length-1&&<b>↓</b>}</div>)}</div><div className="lifecycle-summary"><span>21 DAYS</span><strong>Surface irregularity → deformation → pothole</strong><small>14 observations across 6 buses</small></div></main></>}

function MunicipalMap({open}:{open:(x:RoadDefect)=>void}){const [filter,setFilter]=useState('All');const [selected,setSelected]=useState(defects[0].id);const visible=defects.filter(x=>filter==='All'||x.category===filter);const item=visible.find(x=>x.id===selected);return <div className="map-page municipal-map-page"><div className="map-filter"><FilterBar items={['All','Roads','Infrastructure','Water','Pedestrians']} active={filter} onChange={value=>{setFilter(value);const first=defects.find(x=>value==='All'||x.category===value);if(first)setSelected(first.id)}}/></div><IssueMap items={visible} selected={selected} onSelect={setSelected}/>{item&&<section className="bottom-sheet"><i className="handle"/><span className="sheet-eyebrow">{item.severity.toUpperCase()} · {item.category.toUpperCase()}</span><h3>{item.defectType}</h3><p>{item.location} · {item.status}</p><small>{item.detectionCount} observations · Last seen {item.lastSeen}</small><button className="primary" onClick={()=>open(item)}>Open record</button></section>}</div>}
function IssueMap({items,selected,onSelect}:{items:RoadDefect[];selected:string;onSelect:(id:string)=>void}){const host=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),layer=useRef<L.LayerGroup|null>(null);useEffect(()=>{if(!host.current||map.current)return;map.current=L.map(host.current,{zoomControl:false}).setView([13.005,80.238],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map.current);L.control.zoom({position:'topright'}).addTo(map.current);layer.current=L.layerGroup().addTo(map.current);return()=>{map.current?.remove();map.current=null;layer.current=null}},[]);useEffect(()=>{if(!layer.current)return;layer.current.clearLayers();items.forEach(x=>{const color=x.category==='Water'?'#27749d':x.category==='Infrastructure'?'#6e7040':x.category==='Pedestrians'?'#d07b2e':x.severity==='High'||x.severity==='Critical'?'#b84940':'#7b6136';L.circleMarker([x.latitude,x.longitude],{radius:x.id===selected?11:8,color:'#fff',weight:3,fillColor:color,fillOpacity:1}).bindTooltip(`${x.defectType} · ${x.location}`).on('click',()=>onSelect(x.id)).addTo(layer.current!)});},[items,selected,onSelect]);return <div className="police-geo-map" ref={host} aria-label="Interactive municipal GIS map"/>}

function Planning({selected,duration,onRoad,onDuration,run}:{selected:string;duration:string;onRoad:(id:string)=>void;onDuration:(value:string)=>void;run:()=>void}){const road=roads.find(x=>x.id===selected)!;return <div className="page planning-page"><PageIntro eyebrow="FLEET-DERIVED TRAFFIC BASELINE" title="Urban Planning & What-If"/><Surface className="planning-controls"><strong>1 · Select a road segment on the map</strong><span>Selected: {road.name}</span></Surface><ScenarioMap selected={selected} onSelect={onRoad}/><Surface className="form"><label>Closure / construction duration<select value={duration} onChange={e=>onDuration(e.target.value)}><option>2 weeks</option><option>8 weeks</option><option>4 months</option></select></label><div className="baseline-row"><span>Observed baseline<strong>{road.baseline} traffic</strong></span><span>Fleet sample<strong>1,284 passes</strong></span></div><button className="primary full" onClick={run}><Construction/> Run simulation</button></Surface></div>}
function ScenarioMap({selected,onSelect,result=false}:{selected:string;onSelect?:(id:string)=>void;result?:boolean}){const host=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),layer=useRef<L.LayerGroup|null>(null);useEffect(()=>{if(!host.current||map.current)return;map.current=L.map(host.current,{zoomControl:false}).setView([13.02,80.239],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map.current);layer.current=L.layerGroup().addTo(map.current);return()=>{map.current?.remove();map.current=null;layer.current=null}},[]);useEffect(()=>{if(!layer.current)return;layer.current.clearLayers();roads.forEach((road,index)=>{const active=road.id===selected;const color=active?'#b43a3a':result?(index%2?'#7a2d35':'#d07b2e'):'#315c51';L.polyline(road.points,{color,weight:active?9:6,opacity:.9,dashArray:active?'10 7':undefined}).bindTooltip(active?`${road.name} · SELECTED CLOSURE`:road.name).on('click',()=>onSelect?.(road.id)).addTo(layer.current!)});},[selected,onSelect,result]);return <div className="scenario-map" ref={host} aria-label="Select a road segment for scenario modelling"/>}
function Result({roadId,duration,back,home}:{roadId:string;duration:string;back:()=>void;home:()=>void}){const road=roads.find(x=>x.id===roadId)||roads[0];const multiplier=duration==='4 months'?1.35:duration==='2 weeks'?.8:1;const delay=Math.round(road.delay*multiplier);return <><AppHeader title="Scenario result" subtitle={`${road.name} · ${duration}`} onBack={back} onHome={home}/><main className="page detail"><div className="scenario-compare"><span>BEFORE<strong>{road.baseline}</strong><small>Observed network state</small></span><ArrowRight/><span>DURING CLOSURE<strong>High impact</strong><small>Traffic redistributed</small></span></div><ScenarioMap selected={road.id} result/><div className="impact"><span>ESTIMATED AVERAGE DELAY</span><div><strong>+{delay} min</strong><p>Based on historical fleet travel times</p></div><ul><li>{road.affected[0]} <b>High</b></li><li>{road.affected[1]} <b>Severe</b></li><li>Bus routes affected <b>{road.id==='omr'?'19B, 21D':'5E, 23C'}</b></li></ul></div><Surface><SectionHeader title="Impact over time"/><div className="impact-bars">{[['0–30 min',42],['30–60 min',67],['1–2 hours',88],['Stabilised',72]].map(([label,value])=><div key={label as string}><span>{label}</span><i><b style={{width:`${value}%`}}/></i><strong>+{Math.round(Number(value)*delay/88)} min</strong></div>)}</div></Surface><Surface className="scenario-note"><Construction/><div><strong>Baseline, not prediction</strong><p>Scenario estimates use observed vehicle density, speeds, bottlenecks and bus travel times.</p></div></Surface></main></>}
