import { useState } from 'react';
import { ArrowRight, BusFront, CalendarCheck, CheckCircle2, Construction, Droplets, History, MapPin, TrendingUp, TriangleAlert, Wrench } from 'lucide-react';
import { defects } from '../data/demo';
import { DefectCard } from '../components/cards';
import { BottomSheet, MapLegend, MapView } from '../components/MapView';
import { AppHeader, FilterBar, MetricCard, PageIntro, SectionHeader, SeverityBadge, StatusBadge, Surface, Timeline } from '../components/ui';
export default function MunicipalPages({page,navigate,exit}:{page:string;navigate:(x:string)=>void;exit:()=>void}){const [detail,setDetail]=useState(false);if(detail)return <DefectDetail back={()=>setDetail(false)} goRisk={()=>navigate('risk')}/>;return <><AppHeader title="Municipal Operations" subtitle="Chennai Zone Network · Live" onExit={exit}/><main>{page==='overview'&&<Overview go={navigate} open={()=>setDetail(true)}/>} {page==='defects'&&<Defects open={()=>setDetail(true)}/>} {page==='map'&&<MuniMap open={()=>setDetail(true)}/>} {page==='planning'&&<Planning goRisk={()=>navigate('risk')}/>} {page==='risk'&&<RoadRisk back={()=>navigate('planning')}/>}</main></>}
function Overview({go,open}:{go:(x:string)=>void;open:()=>void}){return <div className="page"><PageIntro eyebrow="FLEET CONDITION MONITORING" title="City road health" text="Latest observations from 238 active buses"/><div className="metric-grid"><MetricCard label="Open defects" value="42"/><MetricCard label="Critical" value="07" tone="critical"/><MetricCard label="Waterlogging" value="05" tone="water"/><MetricCard label="Repair verification" value="08" meta="Pending"/></div><div className="sensor-strip municipal"><BusFront/><div><strong>1,284 road observations today</strong><span>Continuous temporal monitoring across 82% routes</span></div></div><SectionHeader title="Priority defects" action="View all" onAction={()=>go('defects')}/>{defects.slice(0,2).map(x=><DefectCard item={x} key={x.id} onClick={open}/>)}<SectionHeader title="Planning intelligence"/><button className="feature-link" onClick={()=>go('planning')}><TrendingUp/><div><strong>Road risk & construction impact</strong><span>Review degrading segments and plan closures</span></div><ArrowRight/></button></div>}
function Defects({open}:{open:()=>void}){const [f,setF]=useState('All');return <div className="page"><PageIntro eyebrow="DEMO OBSERVATIONS" title="Road defects" text="Detected across city fleet routes"/><FilterBar items={['All','Roads','Water','Infrastructure']} active={f} onChange={setF}/><div className="list-stack">{defects.map(x=><DefectCard item={x} key={x.id} onClick={open}/>)}</div></div>}
function DefectDetail({back,goRisk}:{back:()=>void;goRisk:()=>void}){const x=defects[0];const timeline=[{day:'DAY 1 · 01 SEP',title:'Small surface defect',text:'Initial edge observation · MTC-1830'},{day:'DAY 7',title:'Visible pothole',text:'Repeated across 3 fleet passes'},{day:'DAY 14',title:'Larger pothole',text:'Severity raised to High'},{day:'DAY 20 · TODAY',title:'30% observed growth',text:'Latest pass · MTC-2147'}];return <><AppHeader title="Defect record" subtitle={x.id} onBack={back}/><main className="page detail"><div className="title-row"><div><span className="eyebrow">ROAD SURFACE</span><h1>{x.defectType}</h1><p>{x.location}</p></div><SeverityBadge value="High"/></div><div className="road-frame"><img src={x.image}/><span>CURRENT OBSERVATION</span><em>Today · 16:12 · Bus MTC-2147</em><div className="defect-outline"/></div><div className="stat-band"><div><strong>+30%</strong><span>Growth rate</span></div><div><strong>14</strong><span>Detections</span></div><div><strong>6</strong><span>Buses</span></div></div><Surface><SectionHeader title="Detection history"/><Timeline items={timeline}/></Surface><Surface><SectionHeader title="Repair verification"/><div className="verification"><CalendarCheck/><div><span>Marked repaired · 28 Aug</span><strong>Repair not verified</strong><p>Next bus pass detected continued surface damage on 01 Sep.</p></div></div></Surface><button className="secondary full" onClick={goRisk}>View segment road risk <ArrowRight/></button></main></>}
function MuniMap({open}:{open:()=>void}){const [filter,setFilter]=useState('All');const [sel,setSel]=useState('d1');const m:any[]=[{id:'d1',type:'defect',x:62,y:38,label:'Pothole'},{id:'d2',type:'water',x:35,y:62,label:'Waterlogging'},{id:'d3',type:'defect',x:73,y:71,label:'Road defect'}];return <div className="map-page"><div className="map-filter"><FilterBar items={['All','Roads','Infrastructure','Water']} active={filter} onChange={setFilter}/></div><MapView markers={m} selected={sel} onSelect={setSel}><MapLegend/>{sel&&<BottomSheet eyebrow="HIGH SEVERITY · 14 OBSERVATIONS" title="Pothole · OMR" action="View history" onAction={open}><p>Growing +30% since first observation</p><small><History/> Last observed today at 16:12</small></BottomSheet>}</MapView></div>}
function Planning({goRisk}:{goRisk:()=>void}){const [done,setDone]=useState(false);return <div className="page"><PageIntro eyebrow="PLANNING WORKSPACE" title="Construction impact" text="Evaluate road closure pressure using simulated fleet patterns"/><Surface className="form"><label>Select road<select><option>Main Road A · Anna Salai</option><option>OMR · Segment 12</option></select></label><label>Closure duration<select><option>4 months</option><option>8 weeks</option></select></label><button className="primary full" onClick={()=>setDone(true)}><Construction/> Simulate impact</button></Surface>{done&&<><SectionHeader title="Predicted impact"/><div className="impact"><span>SIMULATION · DEMO MODEL OUTPUT</span><div><strong>+24%</strong><p>Expected congestion increase</p></div><ul><li>Affected roads <b>6</b></li><li>High-risk segments <b>2</b></li><li>Traffic redistribution <b>High</b></li></ul></div><Surface className="recommend"><TriangleAlert/><div><strong>Recommendation</strong><p>Phase construction or prepare alternate traffic management on two surrounding roads.</p></div></Surface></>}<button className="feature-link" onClick={goRisk}><TrendingUp/><div><strong>Open Road Risk</strong><span>View deterioration priorities</span></div><ArrowRight/></button></div>}
function RoadRisk({back}:{back:()=>void}){const rows=[['OMR — Segment 12','Degrading','High','Within 30 days'],['Velachery Main Road','Watch','High','Within 45 days'],['L.B. Road — Segment 4','Stable','Medium','Within 90 days']];return <div className="page"><button className="text-back" onClick={back}>← Planning</button><PageIntro eyebrow="PREDICTIVE MAINTENANCE · DEMO" title="Road Risk" text="Prioritization from observed deterioration trends"/>{rows.map((r,i)=><Surface className="risk" key={r[0]}><div><strong>{r[0]}</strong><StatusBadge value={r[2]}/></div><div className="risk-grid"><span>Condition<b>{r[1]} {i<2?'↑':'→'}</b></span><span>Projected intervention<b>{r[3]}</b></span></div><div className="riskbar"><i style={{width:`${80-i*19}%`}}/></div></Surface>)}</div>}
