import { useState } from 'react';
import { ArrowRight, BusFront, Camera, CheckCircle2, Clock3, Database, FileLock2, LocateFixed, MapPin, Play, ScanLine, ShieldCheck, Siren } from 'lucide-react';
import { incidents, watchlist } from '../data/demo';
import { IncidentCard, WatchlistCard } from '../components/cards';
import { BottomSheet, MapLegend, MapView } from '../components/MapView';
import { AppHeader, ConfidenceIndicator, MetricCard, PageIntro, SectionHeader, SeverityBadge, StatusBadge, Surface } from '../components/ui';

export default function PolicePages({page,navigate,exit}:{page:string;navigate:(p:string)=>void;exit:()=>void}){
 const [detail,setDetail]=useState<string|undefined>();
 if(detail?.startsWith('INC')) return <IncidentDetail onBack={()=>setDetail(undefined)} onMap={()=>navigate('map')}/>;
 if(detail?.startsWith('MAT')) return <MatchDetail onBack={()=>setDetail(undefined)}/>;
 return <><AppHeader title="Police Command" subtitle="Chennai City · Systems operational" onExit={exit}/><main>
 {page==='overview'&&<PoliceOverview go={navigate} open={setDetail}/>} {page==='incidents'&&<IncidentList open={setDetail}/>} {page==='watchlist'&&<Watchlist open={setDetail}/>} {page==='map'&&<PoliceMap open={()=>setDetail('INC-24091')}/>}</main></>
}
function PoliceOverview({go,open}:{go:(x:string)=>void;open:(x:string)=>void}){return <div className="page"><PageIntro eyebrow="LIVE OPERATIONS · DEMO" title="Good evening, Officer" text="Fleet observations across Chennai at 18:45"/><div className="metric-grid"><MetricCard label="Active incidents" value="03" tone="warn"/><MetricCard label="Watchlist matches" value="02" tone="critical"/><MetricCard label="Vehicle detections" value="128" meta="Today"/><MetricCard label="Alerts today" value="17" meta="↑ 4 since 17:00"/></div><div className="sensor-strip"><BusFront/><div><strong>238 buses sensing now</strong><span>82% route coverage · metadata + event frames</span></div><span className="live-dot">LIVE</span></div><SectionHeader title="Priority incident" action="All incidents" onAction={()=>go('incidents')}/><IncidentCard item={incidents[0]} onClick={()=>open(incidents[0].id)}/><SectionHeader title="Recent possible match" action="Watchlist" onAction={()=>go('watchlist')}/><WatchlistCard item={watchlist[0]} onClick={()=>open(watchlist[0].id)}/></div>}
function IncidentList({open}:{open:(x:string)=>void}){const [filter,setFilter]=useState('All');return <div className="page"><PageIntro eyebrow="SECURE EVENT RECORDS" title="Incidents" text="Edge-processed events requiring review"/><div className="segmented">{['All','Active','Resolved'].map(x=><button onClick={()=>setFilter(x)} className={filter===x?'active':''}>{x}</button>)}</div><div className="list-stack">{incidents.filter(x=>filter==='All'||(filter==='Resolved'?x.status==='Resolved':x.status!=='Resolved')).map(x=><IncidentCard item={x} key={x.id} onClick={()=>open(x.id)}/>)}</div></div>}
function IncidentDetail({onBack,onMap}:{onBack:()=>void;onMap:()=>void}){const x=incidents[0];return <><AppHeader title="Incident record" subtitle={x.id} onBack={onBack}/><main className="page detail"><div className="title-row"><div><span className="eyebrow">DETECTED EVENT</span><h1>{x.type.replace(' detected','')}</h1></div><SeverityBadge value={x.severity}/></div><div className="evidence"><img src={x.image}/><div className="bbox vehicle"><span>VEHICLE · 96%</span></div><div className="bbox plate"><span>PLATE · 94%</span></div><button><Play fill="white"/> Review 08 sec clip</button><em>{x.timestamp}</em></div><div className="evidence-meta"><span><ShieldCheck/> Secure event record</span><span><Camera/> Onboard Edge</span></div><Surface className="facts"><div><span>Offending vehicle</span><strong>{x.vehicleType}</strong></div><div><span>Registration</span><strong>{x.registrationNumber}</strong></div><div><span>ANPR confidence</span><strong>{x.registrationConfidence}%</strong></div><div><span>Status</span><StatusBadge value={x.status}/></div></Surface><Surface><SectionHeader title="Event location" action="Open map" onAction={onMap}/><button className="location-row" onClick={onMap}><LocateFixed/><div><strong>{x.location}</strong><span>13.0607° N, 80.2496° E</span></div><ArrowRight/></button></Surface><Surface className="chain"><FileLock2/><div><strong>Chain-of-event metadata</strong><span>Captured by {x.busId} · Route {x.route}<br/>Event frame + short clip uploaded</span></div><CheckCircle2/></Surface><button className="primary full">Assign for investigation</button></main></>}
function Watchlist({open}:{open:(x:string)=>void}){return <div className="page"><PageIntro eyebrow="OFFICER VERIFICATION REQUIRED" title="Watchlist" text="Potential matches from fleet observations"/><div className="summary-line"><span><b>2</b> awaiting review</span><span>Updated 1 min ago</span></div><SectionHeader title="Missing persons"/><WatchlistCard item={watchlist[0]} onClick={()=>open(watchlist[0].id)}/><SectionHeader title="Flagged / stolen vehicles"/><WatchlistCard item={watchlist[1]} onClick={()=>open(watchlist[1].id)}/></div>}
function MatchDetail({onBack}:{onBack:()=>void}){const x=watchlist[0];return <><AppHeader title="Possible match" subtitle={x.id} onBack={onBack}/><main className="page detail"><div className="warning-note"><Siren/><div><strong>Requires officer verification</strong><span>Do not treat confidence as identification.</span></div></div><h1>Possible missing-person match</h1><div className="compare"><figure><img src={x.referenceImage}/><figcaption>REFERENCE IMAGE</figcaption></figure><div>VS</div><figure><img src={x.image}/><ScanLine/><figcaption>DETECTED FRAME</figcaption></figure></div><ConfidenceIndicator value={x.confidence}/><Surface className="facts"><div><span>Location</span><strong>{x.location}</strong></div><div><span>Bus</span><strong>{x.busId}</strong></div><div><span>Timestamp</span><strong>11:24:31</strong></div><div><span>Route</span><strong>{x.route}</strong></div></Surface><div className="action-row"><button className="secondary">Reject match</button><button className="primary">Begin verification</button></div></main></>}
function PoliceMap({open}:{open:()=>void}){const [sel,setSel]=useState('i1');const marks:any[]=[{id:'i1',type:'incident',x:55,y:31,label:'Incident'},{id:'w1',type:'watchlist',x:29,y:50,label:'Match'},{id:'b1',type:'bus',x:66,y:63,label:'Bus'},{id:'b2',type:'bus',x:40,y:71,label:'Bus'}];return <div className="map-page"><div className="map-toolbar"><strong>Operational map</strong><span>4 layers active</span></div><MapView markers={marks} selected={sel} onSelect={setSel}><MapLegend/>{sel&&<BottomSheet eyebrow="HIGH SEVERITY · 18:42" title="Hit-and-run · Anna Salai" action="View incident" onAction={open}><p>Vehicle: TN XX XX 1234 · Confidence 94%</p><small><BusFront/> Detected by MTC-2147 · Onboard Edge</small></BottomSheet>}</MapView></div>}
