import { BusFront, ChevronRight, Clock3, MapPin } from 'lucide-react';
import type { Incident, RoadDefect, WatchlistMatch } from '../types';
import type { MunicipalIssue } from '../types/city';
import { formatDemoDate } from '../domain/time';
import { SeverityBadge, StatusBadge } from './ui';
export function IncidentCard({item,onClick}:{item:Incident;onClick:()=>void}){return <button className="event-card" onClick={onClick}>{item.image&&<img src={item.image} alt={`${item.type} evidence`}/>}<div className="event-main"><div className="card-top"><SeverityBadge value={item.severity}/><StatusBadge value={item.status}/></div><strong>{item.type}</strong><span><MapPin/> {item.location}</span><small><Clock3/> {item.timestamp} <b>·</b> {item.detectionSource==='Citizen report'?'Citizen report':<><BusFront/> {item.busId}</>}</small></div><ChevronRight className="chev"/></button>}
export function DefectCard({item,onClick}:{item:RoadDefect & Partial<Pick<MunicipalIssue,'workflowStage'|'citizenReportId'>>;onClick:()=>void}){
 const latest=item.observations?.at(-1), closed=item.workflowStage==='Closed';
 return <button className="event-card defect-card" onClick={onClick}>{(latest?.image||item.image)&&<div className="defect-thumb"><img src={latest?.image||item.image} alt={`${item.defectType} latest observation`}/></div>}<div className="event-main"><div className="card-top">{!closed&&<SeverityBadge value={item.severity}/>}<StatusBadge value={item.workflowStage==='Admin review'?'Awaiting admin review':item.workflowStage||item.status}/></div><strong>{item.defectType}</strong><span><MapPin/> {item.location}</span><small className="defect-state">{closed?'Verified fixed':item.workflowStage==='Admin review'?'Field team reported resolved':item.citizenReportId?'Citizen-submitted issue':latest?.label||item.currentCondition||item.status}</small><small>{item.citizenReportId?`Reported ${formatDemoDate(item.firstSeen)}`:`Latest ${item.lastSeen} · ${item.detectionCount} observations`}</small></div><ChevronRight className="chev"/></button>;
}
export function WatchlistCard({item,onClick}:{item:WatchlistMatch;onClick:()=>void}){return <button className="watch-card" onClick={onClick}><img src={item.image} alt={`${item.subjectType} possible match`}/><div><span>{item.subjectType}</span><strong>{item.subjectName}</strong><small><MapPin/> {item.location} · {item.timestamp.split('·').at(-1)}</small><em>{item.confidence}% possible match · {item.status}</em></div><ChevronRight/></button>}
