import { chromium, expect } from '@playwright/test';

const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/usr/bin/google-chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const base = process.env.QA_URL || 'http://127.0.0.1:4181';
const screenshot = name => page.screenshot({ path: `/tmp/drishti-gis-${name}.png`, fullPage: true });
const enter = async role => {
  await page.getByRole('button', { name: role, exact: true }).click();
  await page.getByRole('button', { name: 'Enter demo workspace' }).click();
  await page.getByRole('button', { name: 'Map', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Bus movement feed' })).toBeVisible();
};
const heat = () => page.getByRole('region', { name: 'Heat signal summary' });
const loadedTiles = () => page.locator('.leaflet-tile-loaded[src*="arcgisonline.com"]');

try {
  await page.clock.install();
  await page.goto(base);
  await enter('Police');
  await expect.poll(() => loadedTiles().count()).toBeGreaterThan(0);
  await expect(page.locator('.gis-bus-pin')).toHaveCount(10);
  await expect(page.locator('.gis-bus-pin .bus-face')).toHaveCount(60);
  await expect(page.locator('.trail-sequence')).toHaveCount(0);
  await page.getByRole('button', { name: 'Close map record' }).click();
  await page.getByRole('button', { name: 'Fit visible map records' }).click();
  const movingBus = page.locator('.gis-bus-list button').filter({ hasText: 'MTC-2014' });
  const before = await movingBus.textContent();
  await page.clock.runFor(4000);
  expect(await movingBus.textContent()).not.toBe(before);
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  const paused = await movingBus.textContent();
  await page.clock.runFor(2000);
  expect(await movingBus.textContent()).toBe(paused);
  await movingBus.click();
  await expect(page.locator('.gis-bus-pin[aria-label^="MTC-2014"]')).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Heatmap', exact: true }).click();
  await expect(heat().getByRole('status')).toContainText('2active incidents');
  await expect(page.locator('.gis-heat-canvas')).toHaveCount(1);
  await page.getByLabel('Signal', { exact: true }).selectOption('hit-and-run');
  await expect(heat()).toContainText('No matching incidents');
  await expect(page.locator('.gis-heat-canvas')).toHaveCount(0);
  await page.getByLabel('Signal', { exact: true }).selectOption('all');
  await page.getByLabel('Include resolved history').check();
  await expect(heat().getByRole('status')).toContainText('3recorded incidents');
  await page.getByRole('combobox', { name: /jurisdiction/i }).selectOption('central');
  await page.getByRole('button', { name: 'Heatmap', exact: true }).click();
  await expect(heat().getByRole('status')).toContainText('1active incidents');
  await expect(page.locator('.gis-bus-pin')).toHaveCount(2);
  await page.getByRole('button', { name: 'Fit visible map records' }).click();
  await screenshot('police');
  await page.getByRole('button', { name: 'Logout', exact: true }).click();
  await enter('Municipal');
  await expect(page.locator('.gis-bus-pin')).toHaveCount(13);
  await page.getByRole('button', { name: 'Close map record' }).click();
  await page.getByRole('button', { name: 'Heatmap', exact: true }).click();
  await expect(heat().getByRole('status')).toContainText('6active issues');
  await page.getByLabel('Signal', { exact: true }).selectOption('waterlogging');
  await expect(heat().getByRole('status')).toContainText('1active issues');
  await expect(heat()).toContainText('9 detections');
  await page.getByLabel('Signal', { exact: true }).selectOption('pothole');
  await expect(heat()).toContainText('No matching issues');
  await page.getByLabel('Include resolved history').check();
  await expect(heat().getByRole('status')).toContainText('1recorded issues');
  await page.getByLabel('Signal', { exact: true }).selectOption('all');
  await page.getByRole('button', { name: 'Hide buses', exact: true }).click();
  await expect(page.locator('.gis-bus-pin')).toHaveCount(0);
  await page.getByRole('button', { name: 'Fit visible map records' }).click();
  await expect.poll(() => loadedTiles().count()).toBeGreaterThan(0);
  const paintedPixels = await page.locator('.gis-heat-canvas').evaluate(canvas => {
    const rgba = canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height).data;
    let count = 0;
    for (let i = 3; i < rgba.length; i += 4) if (rgba[i]) count++;
    return count;
  });
  expect(paintedPixels).toBeGreaterThan(500);
  await screenshot('municipal');
  await page.locator('.leaflet-control-layers-toggle').click();
  await page.getByLabel('Satellite · Esri', { exact: true }).check();
  await expect.poll(() => page.locator('.leaflet-tile-loaded[src*="World_Imagery"]').count()).toBeGreaterThan(0);
  await page.locator('.gis-map-label').click({ force: true });
  await screenshot('satellite');
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Heatmap', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByLabel('Signal', { exact: true }).selectOption('waterlogging');
  await page.getByRole('button', { name: 'Fit visible map records' }).click();
  await screenshot('mobile');
  await page.getByRole('button', { name: 'Records', exact: true }).click();
  await page.getByRole('button', { name: 'Show buses', exact: true }).click();
  await expect(page.locator('.gis-bus-pin')).toHaveCount(13);
  expect(errors).toEqual([]);
  console.log(JSON.stringify({ result: 'passed', checks: ['keyless Esri tiles', '3D bus models', 'play/pause and locate', 'police jurisdiction', 'incident categories and history', 'municipal recurrence and history', 'canvas heat pixels', 'satellite tiles', '390px responsive layout', 'no runtime errors'], screenshots: '/tmp/drishti-gis-{police,municipal,satellite,mobile}.png' }, null, 2));
} finally {
  await browser.close();
}