import { useState } from 'react';
import { ArrowRight, BusFront, Building2, ChevronRight, Cpu, Navigation, Radio, Shield } from 'lucide-react';
import { navigation } from './navigation/config';
import type { Role } from './types';
import { BottomNavigation } from './components/ui';
import PolicePages from './pages/PolicePages';
import MunicipalPages from './pages/MunicipalPages';
import CitizenPages from './pages/CitizenPages';

export default function App(){const [role,setRole]=useState<Role>('landing');const [page,setPage]=useState('overview');const enter=(r:Role)=>{setRole(r);setPage(r==='citizen'?'traffic':'overview')};if(role==='landing')return <Landing enter={enter}/>;const items=navigation[role];return <div className={`app-shell ${role}`}>{role==='police'?<PolicePages page={page} navigate={setPage} exit={()=>setRole('landing')}/>:role==='municipal'?<MunicipalPages page={page} navigate={setPage} exit={()=>setRole('landing')}/>:<CitizenPages page={page} navigate={setPage} exit={()=>setRole('landing')}/>}<BottomNavigation items={items} active={page} onChange={setPage}/></div>}
function Landing({enter}:{enter:(r:Role)=>void}){const roles=[{id:'police' as Role,label:'Police',sub:'Incidents & Watchlist',icon:Shield},{id:'municipal' as Role,label:'Municipal',sub:'Roads & Infrastructure',icon:Building2},{id:'citizen' as Role,label:'Citizen',sub:'Traffic & Mobility',icon:Navigation}];return <main className="landing"><header><div className="brand-mark"><span>D</span></div><div><strong>DRISHTI</strong><small>AI-POWERED MOBILE URBAN INTELLIGENCE</small></div><span className="demo">DEMO MODE</span></header><section className="hero"><div className="hero-visual"><svg viewBox="0 0 390 230"><path d="M-10 200 C80 155 118 205 195 145 S320 55 410 90"/><path d="M35 240 C90 180 105 110 90 -10"/><path d="M250 240 C220 180 260 105 330 -10"/></svg><div className="bus-orbit"><BusFront/><span>PUBLIC FLEET</span></div><i className="node n1"/><i className="node n2"/><i className="node n3"/><div className="signal"><Radio/>238 sensing</div></div><span className="hero-kicker">ONE FLEET. A CITY OF INSIGHTS.</span><h1>Public transport becomes a moving sensor network.</h1><p>Shared observations support safer roads, responsive services and better journeys.</p><div className="flow" aria-label="Bus cameras to edge processing to city intelligence"><span><BusFront/> Bus cameras</span><ArrowRight/><span><Cpu/> Edge processing</span><ArrowRight/><span>City intelligence</span></div><div className="flow-audiences">POLICE · MUNICIPAL · CITIZENS</div></section><section className="role-section"><div><h2>Select your workspace</h2><span>Choose a role to continue</span></div><div className="role-list">{roles.map(({id,label,sub,icon:Icon})=><button onClick={()=>enter(id)} key={id}><i><Icon/></i><div><strong>{label}</strong><span>{sub}</span></div><ChevronRight/></button>)}</div></section><footer><span>SIMULATED DATA ENVIRONMENT</span><b><i/> Platform operational</b></footer></main>}
